### ISSUE TITLE
Octave complains on missing libgraphicsmagick++.so

### ISSUE THREAD

**Issue by Germanc** [its-pointless/its-pointless.github.io#1]
I found your repo by chance. Installed octave and it complains on missing libGraphicsMagick++.so.  I just started to use termux so I'm not sure on where to look up that library

**Comment by its-pointless** [comment]
i will fix it in a second with a libgraphicsmagick++ package 
thought i tested it properly..
obviously not.

**Comment by Germanc** [comment]
Installed graphicsmagick++ and now it works. That was fast, thank you !
