### ISSUE TITLE
octave cannot locate symbol powisf2

### ISSUE THREAD

**Issue by cyh-ustc** [its-pointless/its-pointless.github.io#10]
$ octave
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.4.0": cannot locate symbol "__powisf2" referenced by "/data/data/com.termux/files/usr/lib/octave/4.4.0/liboctave.so"...
Aborted
$

**Comment by its-pointless** [comment]
Which arch?
Im guessing x86 of some kind?

**Comment by cyh-ustc** [comment]
sorry
forget to provide device info
arch: arm64(snapdragon 821)
lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           2
Vendor ID:           Qualcomm
Model:               1
Model name:          Kryo
Stepping:            0x2
CPU max MHz:         2342.3999
CPU min MHz:         307.2000
BogoMIPS:            38.00
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32
$ uname -a
Linux localhost 3.18.116-BlackScreen-5.3 #1 SMP PREEMPT Thu Aug 2 03:44:28 UTC 2018 aarch64 Android

**Comment by its-pointless** [comment]
K uploading openblas with that symbol....
