### ISSUE TITLE
Julia-1.0.1 and libllvm-julia-6.0.0-1 on arm have a symbol problem

### ISSUE THREAD

**Issue by Laoyian** [its-pointless/its-pointless.github.io#16]
Error message：
CANNOT LINK EXECUTABLE "julia": cannot locate symbol "LLVMInitializeWebAssemblyTargetMC" referenced by "/data/data/com.termux/files/usr/opt/julia/lib/libjulia.so.1.0"

**Comment by its-pointless** [comment]
Should be fixed
