### ISSUE TITLE
OpenCV package has import error

### ISSUE THREAD

**Issue by Rybec** [its-pointless/its-pointless.github.io#18]
It appears that the OpenCV package found [here](https://github.com/its-pointless/its-pointless.github.io/blob/master/files/dists/termux/extras/binary-aarch64/opencv_4.0.0_aarch64.deb) seems to have the same bug as 3.4.4-1, reported here: https://bugs.archlinux.org/task/60855

**Comment by Rybec** [comment]
I should add: Compiling from source is not an option for me.  I have tried this, and everything works up until it gets to linking.  My device has only 1GB of ram, which is not enough, and there are no resources for rooting it, which makes adding swap impossible.  The only remaining option is to find a working binary.

**Comment by its-pointless** [comment]
Try 
`mv /data/data/com.termux/files/usr/python/cv2/python-3.7/cv2.cpython-37m-x86_64-linux-gnu.so /data/data/com.termux/files/usr/python/cv2/python-3.7/cv2.so`

**Comment by Rybec** [comment]
That seems to have worked!  Thank you!

(I'll let you decide whether you just want to close this or leave it open as a reminder to fix the .deb, if you intend on doing that.)

**Comment by its-pointless** [comment]
Works fine now
