### ISSUE TITLE
octave pkg install fails

### ISSUE THREAD

**Issue by HJarausch** [its-pointless/its-pointless.github.io#2]
Hi,
having installed octave on my tablet I tried
pkg install - forgé interval

But there is the common problem that (make) scripts use  /usr/bin/sh
which would have to be fixed on Termux.
How can I do that?

Many thanks,
Helmut

**Comment by its-pointless** [comment]
normally i would say download the package directly extract it make edits then tar -cf interval.tar and then start octave and use pkg install interval.tar
and that would work
iv recently come across soemthing better though.  https://raw.githubusercontent.com/its-pointless/gcc_termux/master/libandroid-fixshebang.c
compile as a lib gcc libandroid-fixshebang.c -shared -o libandroid-fixshebang.so 
then execute 
LD_PRELOAD=$(pwd)/libandroid-fixshebang.so ~/.termux/shell 
this will make /bin/sh command execute $PREFIX/bin/sh and /usr/bin/env execute $PREFIX/bin/env in the new shell. 
either of those will work also you might want to `export JOBS=4` before using octave so make will use  -j 4 when compiling, speed it up hopefully if you have 4 cores etc.  
anyway hope that helps.

**Comment by HJarausch** [comment]
Many thanks for that GREAT hint.
I had just to replace  ~/.termux/shell  by
/data/data/com.termux/files/usr/bin/bash
Thanks for providing this repository,
Helmut
