### ISSUE TITLE
Octave update 4.4.1-5 broken (Readline needs to be upgraded too) 

### ISSUE THREAD

**Issue by dipayand** [its-pointless/its-pointless.github.io#20]
octave: no graphical display found
octave: disabling GUI features
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/octave-cli-4.4.1": library "libreadline.so.8" not found
Aborted

**Comment by its-pointless** [comment]
Yeah on aarch64 its already updated to readline version 8 but not on other archs... sorry bout that.

**Comment by dipayand** [comment]
when can we expect it on armv7l.. or how do I downgrade it

**Comment by its-pointless** [comment]
Get this file https://github.com/its-pointless/gcc_termux/raw/master/libreadline.8.0.arm
cp  libreadline.8.0.arm $PREFIX/lib/libreadline.so.8

**Comment by its-pointless** [comment]
when readline updates it will over right that file but everthing will still work.

**Comment by dipayand** [comment]
Thank you so much... 😊😊 It works now..
