### ISSUE TITLE
Import error scipy 64-bit instead of 32-bit

### ISSUE THREAD

**Issue by dekubi** [its-pointless/its-pointless.github.io#21]
ImportError: dlopen failed: "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-armv8l.egg/scipy/_lib/_ccallback_c.cpython-37m.so" is 64-bit instead of 32-bit

**Comment by dekubi** [comment]
@its-pointless scipy 1.2.1 latest version errors whenever I try to import it.
I can't seem to downgrade to any old version.
Any help on how to fix the errors or downgrade to an old version

**Comment by dekubi** [comment]
@its-pointless when i run echo "import scipy" | python
The full error code is, 
echo "import scipy" | python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-armv8l.egg/scipy/__init__.py", line 119, in <module>
    from scipy._lib._ccallback import LowLevelCallable
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-armv8l.egg/scipy/_lib/_ccallback.py", line 1, in <module>
    from . import _ccallback_c
ImportError: dlopen failed: "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-armv8l.egg/scipy/_lib/_ccallback_c.cpython-37m.so" is 64-bit instead of 32-bit

**Comment by its-pointless** [comment]
Fix it in a few mins

**Comment by dekubi** [comment]
@its-pointless Thanks for your support and great work.

**Comment by its-pointless** [comment]
K upped fixed version it has same file name.

**Comment by dekubi** [comment]
Am on upgrading it.

**Comment by dekubi** [comment]
It up and running great. Thank you once again

**Comment by dekubi** [comment]
@its-pointless, how do i set the gcc-8 and g++-8 as the default compiler on Termux?

**Comment by its-pointless** [comment]
setupgcc-8, setupclang and setupclang-gfort-8 commands switch compiler

**Comment by dekubi** [comment]
Great

**Comment by dekubi** [comment]
@its-pointless Do you have any hacks for installing scikit-learn on termux

**Comment by its-pointless** [comment]
Scikit-learn needs multiprocessing python  module which doesn't work on android due to lack of working sem_open.

**Comment by HeRo002** [comment]
The above communication seems to indicate that someone created a 32-bit version of scipy (for Android), but where do I find it...?
