### ISSUE TITLE
GNU Octave 5.0.1 crashes on wrong command

### ISSUE THREAD

**Issue by dipayand** [its-pointless/its-pointless.github.io#22]
Octave. 5.1.0
octave: no graphical display found
octave: disabling GUI features
GNU Octave, version 5.1.0
Copyright (C) 2019 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.  For details, type 'warranty'.

Octave was configured for "arm-unknown-linux-androideabi".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
For information about changes from previous versions, type 'news'.

>> lw
error: 'lw' undefined near line 1 column 1
fatal: caught signal Segmentation fault -- stopping myself...
Segmentation fault

**Comment by its-pointless** [comment]
hmm that has happened before but it seems only to affect arm here.

**Comment by its-pointless** [comment]
i found the cause its because libhdf5 is compiled without -fexceptions ...

**Comment by its-pointless** [comment]
https://github.com/its-pointless/gcc_termux/blob/master/libhdf5_1.10.1-2_arm.deb should fix it...
