### ISSUE TITLE
setup-pointless-repo.sh (is this required anymore at first time installation of termux) 

### ISSUE THREAD

**Issue by dipayand** [its-pointless/its-pointless.github.io#23]
Reading package lists... Done
E: The repository 'https://its-pointless.github.io/files termux Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by its-pointless** [comment]
Whoops

**Comment by its-pointless** [comment]
I can't reproduce it.
you have to add gpg key again if you reinstall.
