### ISSUE TITLE
32-bit R install.packages aborts

### ISSUE THREAD

**Issue by tacitean** [its-pointless/its-pointless.github.io#25]
Latest upgrade of the 32-bit r-base seems to have broken install.packages, which aborts every time.
The 64-bit version is working fine

**Comment by its-pointless** [comment]
whats the error?

**Comment by tacitean** [comment]
It lets you select a CRAN mirror and successfully downloads the *.tar.gz archive, then prints

Downloaded 8734 bytes

Aborted

the downloaded packages are in [...]
Updating HTML index of packages in '.Library'
Warning message:
In install.packages'(bitops') ;
 installation of package 'bitops' had non-zero exit status

Occurs with all packages and all mirrors

**Comment by tacitean** [comment]
Latest version:

Error: package or namespace load failed for ‘utils’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
Error: package or namespace load failed for ‘stats’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found
2: package ‘stats’ in options("defaultPackages") was not found

**Comment by its-pointless** [comment]
i can't reproduce this.
