### ISSUE TITLE
eFTE ncurses editor compiled and works in Termux

### ISSUE THREAD

**Issue by kveroneau** [its-pointless/its-pointless.github.io#26]
Hi.  I am not sure how to contribute build scripts to have a new package introduced into the extras repository.  It took me some time to get it compiled, as it builds 3 binaries, one for X11, one for the Linux VC, and one for ncurses.  It builds using CMake, so I needed to also familiarize myself with how to configure the build correctly.

efte repo: https://github.com/lanurmi/efte/

In order to have it compiled, lines 227-233 need to be completely removed as Android doesn't have Linux console support, so when it tries to build vefte it will fail, and will most likely not even run anyways.

The dependencies needed to build it were: cmake and ncurses-dev.  There might be a few others, however my Termux install had everything but these two.  The code itself is C++, so that compiler and related libraries are also required to build.

The CMake build command I used is as follows:

$ cmake . -DCMAKE_INSTALL_PREFIX=/data/data/com.termux/files/usr -DUSE_GPM=OFF

GPM isn't needed to make use of efte's excellent mouse support, as the ANSI/VT100 specification has full mouse support and works fully in Termux to navigate menus and dialog boxes within the app.

Overall, this editor is great to have on Termux, and fits right in next to Midnight Commander, as efte has a similar colour scheme which can be applied.  It's a very user-friendly editor that also supports full syntax highlighting out of the box for most popular languages and scripting formats.  Also, being menu based, and supported by the Android touchscreen, it makes it easier to save, exit, and use other common editing features without needing to use a special android keyboard or have the Termux shortcut bar constantly on-sceen, giving more screen real estate to the code editor.

**Comment by kveroneau** [comment]
Okay, so I found one unfortunate issue which I am unable to currently solve.  I checked "stty" and my "TERM" environment variable and still am unsure why I cannot get backspace to work correctly in nefte.  Any ideas?  When I press backspace on my Android keyboard, it works fine in bash, and in nano, but in nefte it displays a "^?" which is my backspace character according to stty, is termcap available in Termux?

**Comment by its-pointless** [comment]
Its likely not using utf-8 or something like that.

**Comment by its-pointless** [comment]
Also i recall having similar issue with wordgrinder when it wasn't linking to libandroid-support. Adding  
`-landroid-support` when configuring fixed it there.

**Comment by kveroneau** [comment]
Hmm, so if I use the Ctrl-h combo, it acts like the backspace key.  But stty has Ctrl-? Set, and ctrl-? Works fine in bash, nano, and other programs.  On my PC my stty is set ctrl-? As the backspace key, and nefte works fine.

Interesting suggestion in trying to build against android-support.  I'll give that a shot and report my findings.  Odd issue overall.

**Comment by kveroneau** [comment]
Not sure if you saw my updates I placed into my previous comment above.  Today I am going to dive into the source for nefte to see how the backspace key is handled.  This morning I tried Termux on my phone using a physical keyboard through Samsung DeX, and the backspace key had the same issue unfortunately.  Although through Linux on DeX using the ubuntu ARM package it works fine.  So it is something related to either how Termux tells programs how to handle backspace, a library such as ncursesw just isn't tested with nefte, or something else I'm missing.

**Comment by its-pointless** [comment]
K the issue is you want to compile without locale support. -DUSE_LOCALE=off when invoking cmake

**Comment by its-pointless** [comment]
oh no im wrong...

**Comment by its-pointless** [comment]
solution ?
https://gist.github.com/its-pointless/15a5274eb6cc5106b691793912a8fc32

**Comment by kveroneau** [comment]
Thank you so much!  That patch worked.  It compiled no problem, and the backspace key functions as expected through Termux.
