### ISSUE TITLE
scipy ImportError: library "libandroid-support.so" not found

### ISSUE THREAD

**Issue by chenyulue** [its-pointless/its-pointless.github.io#27]
After installing `scipy`,  I get the following error when `import  scipy`:

> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-aarch64.egg/scipy/__init__.py", line 119, in <module>
>     from scipy._lib._ccallback import LowLevelCallable
>   File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/scipy-1.2.1-py3.7-linux-aarch64.egg/scipy/_lib/_ccallback.py", line 1, in <module>
>     from . import _ccallback_c
> ImportError: dlopen failed: library "libandroid-support.so" not found

My installed package on my phone are:

> apt/stable,now 1.4.9-4 aarch64 [installed]
> bash/stable,now 5.0.7 aarch64 [installed]
> binutils/stable,now 2.32-2 aarch64 [installed,automatic]
> busybox/stable,now 1.30.1-1 aarch64 [installed]
> ca-certificates/stable,now 20190124 all [installed]
> clang/stable,now 8.0.0-2 aarch64 [installed]
> command-not-found/stable,now 1.37 aarch64 [installed]
> coreutils/stable,now 8.31 aarch64 [installed]
> curl/stable,now 7.64.1-1 aarch64 [installed]
> dash/stable,now 0.5.10.2-1 aarch64 [installed]
> diffutils/stable,now 3.7 aarch64 [installed,automatic]
> dnsutils/stable,now 9.13.6-3 aarch64 [installed]
> dpkg/stable,now 1.19.4-1 aarch64 [installed]
> fftw/stable,now 3.3.8 aarch64 [installed]
> fftw-dev/stable,now 3.3.8 aarch64 [installed]
> freetype/stable,now 2.10.0-1 aarch64 [installed]
> freetype-dev/stable,now 2.10.0-1 aarch64 [installed]
> game-repo/stable,now 1.1 all [installed]
> gdbm/stable,now 1.18.1 aarch64 [installed,automatic]
> getconf/stable,now 0.5 aarch64 [installed]
> git/stable,now 2.21.0-2 aarch64 [installed]
> glib/stable,now 2.58.3-2 aarch64 [installed,automatic]
> gnupg/stable,now 2.2.15-1 aarch64 [installed]
> gpgv/stable,now 2.2.15-1 aarch64 [installed]
> krb5/stable,now 1.16.3-1 aarch64 [installed,automatic]
> ldns/stable,now 1.7.0-5 aarch64 [installed,automatic]
> less/stable,now 530-2 aarch64 [installed]
> libandroid-glob/stable,now 0.4 aarch64 [installed,automatic]
> libandroid-glob-dev/stable,now 0.4 aarch64 [installed]
> libandroid-shmem/stable,now 0.2 aarch64 [installed]
> libandroid-shmem-dev/stable,now 0.2 aarch64 [installed]
> libandroid-support/stable,now 24 aarch64 [installed]
> libassuan/stable,now 2.5.3 aarch64 [installed,automatic]
> libbz2/stable,now 1.0.6-2 aarch64 [installed]
> libc++/stable,now 19b aarch64 [installed]
> libcrypt/stable,now 0.2-1 aarch64 [installed,automatic]
> libcrypt-dev/stable,now 0.2-1 aarch64 [installed,automatic]
> libcurl/stable,now 7.64.1-1 aarch64 [installed]
> libdb/stable,now 18.1.32 aarch64 [installed,automatic]
> libedit/stable,now 20190324-3.1-0 aarch64 [installed,automatic]
> libffi/stable,now 3.2.1-2 aarch64 [installed,automatic]
> libgcrypt/stable,now 1.8.4 aarch64 [installed]
> libgfortran5/termux,now 8.3.0-2 aarch64 [installed,automatic]
> libgpg-error/stable,now 1.36 aarch64 [installed]
> libksba/stable,now 1.3.5-1 aarch64 [installed,automatic]
> libllvm/stable,now 8.0.0-2 aarch64 [installed,automatic]
> liblzma/stable,now 5.2.4 aarch64 [installed]
> libnghttp2/stable,now 1.38.0 aarch64 [installed]
> libnpth/stable,now 1.6 aarch64 [installed,automatic]
> libpng/stable,now 1.6.37-1 aarch64 [installed]
> libpng-dev/stable,now 1.6.37-1 aarch64 [installed]
> libsodium/stable,now 1.0.17 aarch64 [installed,automatic]
> libsqlite/stable,now 3.27.2-1 aarch64 [installed,automatic]
> libtalloc/stable,now 2.1.14-1 aarch64 [installed,automatic]
> libunistring/stable,now 0.9.10-1 aarch64 [installed,automatic]
> libuuid/stable,now 1.0.3-2 aarch64 [installed,automatic]
> libzmq/stable,now 4.3.1-1 aarch64 [installed]
> libzmq-dev/stable,now 4.3.1-1 aarch64 [installed]
> ncurses/stable,now 6.1.20181117-1 aarch64 [installed]
> ncurses-ui-libs/stable,now 6.1.20181117-1 aarch64 [installed,automatic]
> ndk-sysroot/stable,now 19b-3 aarch64 [installed,automatic]
> numpy/termux,now 1.16.2 aarch64 [installed]
> openblas/termux,now 0.3.5 aarch64 [installed,automatic]
> openssh/stable,now 8.0p1-1 aarch64 [installed]
> openssl/stable,now 1.1.1b-2 aarch64 [installed]
> openssl-tool/stable,now 1.1.1b-2 aarch64 [installed]
> pcre/stable,now 8.43-1 aarch64 [installed,automatic]
> pcre2/stable,now 10.33 aarch64 [installed,automatic]
> pinentry/stable,now 1.1.0-2 aarch64 [installed,automatic]
> pkg-config/stable,now 0.29.2 aarch64 [installed]
> proot/stable,now 5.1.107-20 aarch64 [installed]
> pv/stable,now 1.6.6 aarch64 [installed]
> python/stable,now 3.7.3-1 aarch64 [installed]
> python-dev/stable,now 3.7.3-1 aarch64 [installed]
> readline/stable,now 8.0 aarch64 [installed]
> resolv-conf/stable,now 1.2 aarch64 [installed,automatic]
> science-repo/stable,now 1.0 all [installed]
> scipy/termux,now 1.2.1-1 aarch64 [installed]
> tar/stable,now 1.32-1 aarch64 [installed]
> termux-am/stable,now 0.2 all [installed]
> termux-auth/stable,now 1.1 aarch64 [installed,automatic]
> termux-exec/stable,now 0.4 aarch64 [installed]
> termux-keyring/stable,now 1.2 all [installed]
> termux-tools/stable,now 0.65 all [installed]
> tsu/stable,now 2.3 all [installed]
> vim/stable,now 8.1.1200-1 aarch64 [installed]
> vim-runtime/stable,now 8.1.1200-1 all [installed,automatic]
> wget/stable,now 1.20.3-1 aarch64 [installed]
> xz-utils/stable,now 5.2.4 aarch64 [installed,automatic]
> zip/stable,now 3.0-2 aarch64 [installed]
> zlib/stable,now 1.2.11-3 aarch64 [installed]
> zlib-dev/stable,now 1.2.11-3 aarch64 [installed]
> zsh/stable,now 5.7.1 aarch64 [installed]

I've installed `libandroid-support`, So I'm confused about what else I can do. 

Can you give me some suggestions? 

Thx

**Comment by chenyulue** [comment]
`export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib` solves my problem.

**Comment by YEDrekt** [comment]
> `export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib` solves my problem.

For me, executing this command and trying to `import cv2` gives me a different error:
`export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`

Any ideas about how to fix this?
