### ISSUE TITLE
gcc 8 errors termux

### ISSUE THREAD

**Issue by dekubi** [its-pointless/its-pointless.github.io#28]
included from /data/data/com.termux/files/usr/include/features.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/__config:204,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:37,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:205:9: error: attributes are not allowed on a function-definition
         __prefer_this_overload {
         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /data/data/com.termux/files/usr/include/c++/v1/string.h:61,
                 from /data/data/com.termux/files/usr/include/stdio.h:47,
                 from /data/data/com.termux/files/usr/include/c++/v1/stdio.h:108,
                 from /data/data/com.termux/files/usr/include/wchar.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/wchar.h:119,
                 from /data/data/com.termux/files/usr/include/c++/v1/iosfwd:90,
                 from /data/data/com.termux/files/usr/include/c++/v1/ios:215,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:38,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:204:13: error: ambiguating new declaration of 'const void* memchr(const void*, int, size_t)'
 const void* memchr(const void* const s __pass_object_size, int c, size_t n)
             ^~~~~~
/data/data/com.termux/files/usr/include/string.h:45:7: note: old declaration 'void* memchr(const void*, int, size_t)'
 void* memchr(const void* __s, int __ch, size_t __n) __attribute_pure__;
       ^~~~~~
In file included from /data/data/com.termux/files/usr/include/features.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/__config:204,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:37,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:210:65: error: attributes are not allowed on a function-definition
 void* memchr(void* const s __pass_object_size, int c, size_t n) __prefer_this_overload {
                                                                 ^~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/string.h:221:9: error: attributes are not allowed on a function-definition
         __prefer_this_overload {
         ^~~~~~~~~~~~~~~~~~~~~~
In file included from /data/data/com.termux/files/usr/include/c++/v1/string.h:61,
                 from /data/data/com.termux/files/usr/include/stdio.h:47,
                 from /data/data/com.termux/files/usr/include/c++/v1/stdio.h:108,
                 from /data/data/com.termux/files/usr/include/wchar.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/wchar.h:119,
                 from /data/data/com.termux/files/usr/include/c++/v1/iosfwd:90,
                 from /data/data/com.termux/files/usr/include/c++/v1/ios:215,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:38,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:220:13: error: ambiguating new declaration of 'const char* strchr(const char*, int)'
 const char* strchr(const char* const s __pass_object_size, int c)
             ^~~~~~
/data/data/com.termux/files/usr/include/string.h:65:7: note: old declaration 'char* strchr(const char*, int)'
 char* strchr(const char* __s, int __ch) __attribute_pure__;
       ^~~~~~
In file included from /data/data/com.termux/files/usr/include/features.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/__config:204,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:37,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:227:9: error: attributes are not allowed on a function-definition
         __prefer_this_overload {
         ^~~~~~~~~~~~~~~~~~~~~~
/data/data/com.termux/files/usr/include/string.h:237:68: error: attributes are not allowed on a function-definition
 const char* strrchr(const char* const s __pass_object_size, int c) __prefer_this_overload {
                                                                    ^~~~~~~~~~~~~~~~~~~~~~
In file included from /data/data/com.termux/files/usr/include/c++/v1/string.h:61,
                 from /data/data/com.termux/files/usr/include/stdio.h:47,
                 from /data/data/com.termux/files/usr/include/c++/v1/stdio.h:108,
                 from /data/data/com.termux/files/usr/include/wchar.h:33,
                 from /data/data/com.termux/files/usr/include/c++/v1/wchar.h:119,
                 from /data/data/com.termux/files/usr/include/c++/v1/iosfwd:90,
                 from /data/data/com.termux/files/usr/include/c++/v1/ios:215,
                 from /data/data/com.termux/files/usr/include/c++/v1/iostream:38,
                 from main.cpp:1:
/data/data/com.termux/files/usr/include/string.h:237:13: error: ambiguating new declaration of 'const char* strrchr(const char*, int)'
 const char* strrchr(const char* const s __pass_object_size, int c) __prefer_this_overload

**Comment by dekubi** [comment]
@its-pointless this error has been bugging me down for a while now, any help yet since my last post

**Comment by its-pointless** [comment]
Execute command
setup-patchforgcc

**Comment by dekubi** [comment]
I have run setup-patchforgcc but still the bug persist

**Comment by its-pointless** [comment]
Does this line 
#if defined(__cplusplus) && defined(__clang__)
exist in the string.h file in include dir?

**Comment by dekubi** [comment]
patching headers with /data/data/com.termux/files/usr/share/setup_scripts/stdio.h-gcc-compat.patch
Possibly reversed hunk 1 at 279
Hunk 1 FAILED 183/183.
 #endif
 #endif

-#if defined(__BIONIC_INCLUDE_FORTIFY_HEADERS)
+// fortify is now broken in gcc
+#if defined(__BIONIC_INCLUDE_FORTIFY_HEADERS)
+#if defined(__clang__)
 #include <bits/fortify/string.h>
+#else
+#error "fortify doesn't work for gcc"
+#endif
 #endif
-
 /* Const-correct overloads. Placed after FORTIFY so we call those functions, if possible. */
-#if defined(__cplusplus)
+// broken and not even used for gcc when it was part of ndk.
+#if defined(__cplusplus) && defined(__clang__)
 /*
  * Use two enable_ifs so these overloads don't conflict with + are preferred over libcxx's. This can
  * be reduced to 1 after libcxx recognizes that we have const-correct overloads.
patching headers with /data/data/com.termux/files/usr/share/setup_scripts/string.h-gcc-compat.patch

**Comment by dekubi** [comment]
Yes

**Comment by its-pointless** [comment]
okay currently new patches for in setupscript will fix this since if its not clang it will undefine fortity.
