### ISSUE TITLE
R 3.6.0

### ISSUE THREAD

**Issue by bobdadada** [its-pointless/its-pointless.github.io#29]
When I exec R, "utile" and "stats" packages can't be found

**Comment by its-pointless** [comment]
Which arch and using android-5 repo(termux.net) or android-7(bintray 24)?

**Comment by bobdadada** [comment]
aarch64 Android. After I downgrade the version of R to 3.5.3, everything is ok.

**Comment by l1t1** [comment]
same problem, install.packages() not found too.
@bobdadad how to downgrade the version of R to 3.5.3

**Comment by l1t1** [comment]
my os: android 7.1.1

**Comment by bobdadada** [comment]
use `pkg install R=3.5.3`. you may need to remove the installed R.

**Comment by l1t1** [comment]
pkg install R=3.5.3
 returns
E: Unable to locate pckage R,
btw i install 3.6 with `pkg in r-base`

**Comment by l1t1** [comment]
pkg in r-base=3.5.3
works, neednt uninstall 3.6 first

**Comment by l1t1** [comment]
installed 3.5.3, everything is good.
it's platform aarch64-unknown-linux-gnu,
the bad 3.6's platform aarch64-unknown-linux-android

**Comment by l1t1** [comment]
install.packages("sqldf") in 3.5.3 failed

**Comment by bobdadada** [comment]
everything is ok in my android. Did you config your compiler correctly? Maybe a lack of Library dependency. Read info carefully

**Comment by l1t1** [comment]
Thanks, i pkg in make and clang, it works now

**Comment by l1t1** [comment]
R CMD INSTALL data.table_1.12.2.tar.gz  success

**Comment by l1t1** [comment]
3.6.1 error too

The following packages will be upgraded:
  r-base
1 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
Need to get 40.3 MB of archives.
After this operation, 791 kB of additional disk space will be used.
Get:1 https://its-pointless.github.io/files termux/extras aarch64 r-base aarch64 3.6.1 [40.3 MB]
Fetched 40.3 MB in 14min 33s (46.1 kB/s)
(Reading database ... 4957 files and directories currently installed.)
Preparing to unpack .../r-base_3.6.1_aarch64.deb ...
Unpacking r-base (3.6.1) over (3.5.3) ...
Setting up r-base (3.6.1) ...
$ R

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: armv8l-unknown-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

Error: package or namespace load failed for ‘utils’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
Error: package or namespace load failed for ‘stats’:
 .onLoad failed in loadNamespace() for 'utils', details:
  call: system(paste(which, shQuote(names[i])), intern = TRUE, ignore.stderr = TRUE)
  error: error in running command
During startup - Warning messages:
1: package ‘utils’ in options("defaultPackages") was not found
2: package ‘stats’ in options("defaultPackages") was not found

**Comment by its-pointless** [comment]
only way i have been able to reproduce this error is by using the wrong repo. Using android-7 aka packages from this http://dl.bintray.com/termux/termux-packages-24 in main packages but r-base from  https://its-pointless.github.io/files/  
if you are using packages from http://dl.bintray.com/termux/termux-packages-24  you have to use https://its-pointless.github.io/files/24 as repo for R.

**Comment by l1t1** [comment]
add 24 is worse
```
you want to continue? [Y/n]
Get:1 https://its-pointless.github.io/files/24 termux/extras aarch64 r-base aarch64 3.6.1 [40.3 MB]
Fetched 40.3 MB in 5min 47s (116 kB/s)
Selecting previously unselected package debianutils.
(Reading database ... 4967 files and directories currently installed.)
Preparing to unpack .../debianutils_4.8.6.1_aarch64.deb ...
Unpacking debianutils (4.8.6.1) ...
Preparing to unpack .../r-base_3.6.1_aarch64.deb ...
Unpacking r-base (3.6.1) over (3.6.1) ...
Setting up debianutils (4.8.6.1) ...
Setting up r-base (3.6.1) ...
$ R
CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "liblzma.so.5" not found
Aborted
$
```

**Comment by l1t1** [comment]
my  sources.list
```
$ cat $PREFIX/etc/apt/sources.list
# The main termux repository:
#deb https://termux.net stable main
deb [trusted=yes] https://its-pointless.github.io/files/24 termux extras

deb [arch=all,aarch64] http://mirrors.tuna.tsinghua.edu.cn/termux stable main
```

**Comment by l1t1** [comment]
wget -c https://its-pointless.github.io/files/dists/termux/extras/binary-aarch64/r-base_3.5.3_aarch64.deb is good

**Comment by its-pointless** [comment]
i can reproduce this now. 
its not executing which properly debianutils which has a version of which is not installed...
