### ISSUE TITLE
Rust needs to be rebuilt against llvm-5.0

### ISSUE THREAD

**Issue by kirillrdy** [its-pointless/its-pointless.github.io#3]
Currently if you install rustc from this repo and try to run it,
I get 
```
CANNOT LINK EXECUTABLE "rustc": library "libLLVM-4.0.so" not found
```

I suspect this is because main termux repository moved to llvm-5.0, so hopefully just rebuilding rust will be sufficient.

Cheers

**Comment by its-pointless** [comment]
Its why i made a package called libllvm-4so. Install that and it should be fine

**Comment by its-pointless** [comment]
Regardijg just rebuilding... no can do. Waiting on rust to support llvm-5.

**Comment by its-pointless** [comment]
fixing the dependencies would require me rebuilding rust.... 
that takes a long time and i don't have full access to a pc to do that. since i would take several hours.... 
im too lazy for now.

**Comment by its-pointless** [comment]
K iv upped working afaik rustc.
