### ISSUE TITLE
how to install scipy since *-dev packages won't be available for installation

### ISSUE THREAD

**Issue by 12Tall** [its-pointless/its-pointless.github.io#32]
when I installing `numpy` and `scipy`  as:
```shell
$ curl -L https://its-pointless.github.io/setup-pointless-repo.sh | sh
pkg install numpy scipy
```
then,the terminal print:
```shell
....
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
numpy : Depends: python-dev but it is not installable
         Depends: libcrypt-dev but it is not installable
E: Unable to correct problems, you have held broken packages.
```

I tried to install `python-dev` but failed:
```shell
......
Package python-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python

E: Package 'python-dev' has no installation candidate
```

finally, I find this answer in [termux-app issue#1188](https://github.com/termux/termux-app/issues/1188): `*-dev` packages will no longer be available for installation.  

so, I want to ask how can I install `scipy` now, thanks

**Comment by its-pointless** [comment]
oh right will fix up everything soonish.
in a day or 2...

**Comment by hankso** [comment]
The latest version of package python from source `dl.bintray.com/termux/termux-packages-24` is 3.7.4-1.

`apt-cache` shows it replaces package python-dev. That's why you cannot install python-dev explicitly.

**Comment by AIOT-CAT** [comment]
in my termux, i can't find anyone -dev in the pkg list-all, wuwuwu~
