### ISSUE TITLE
r-base error "cannot locate symbol"

### ISSUE THREAD

**Issue by ronnac** [its-pointless/its-pointless.github.io#37]
I ran "pkg upgrade" and "pkg install r-base".
When I launch R I get the following error:

_Error: package or namespace load failed for ‘stats’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data/data/com.termux/files/usr/lib/R/library/stats/libs/stats.so':
  dlopen failed: cannot locate symbol "__aeabi_d2ulz" referenced by "/data/data/com.termux/files/usr/lib/R/library/stats/libs/stats.so"...
During startup - Warning message:
package ‘stats’ in options("defaultPackages") was not found_

**Comment by its-pointless** [comment]
__aeabi_d2ulz
that is part of libcompiler_rt.so 
hmm i guess i still need to link against it even if i am using gcc to compile R. 
k i will fix it at some point in next couple of days

**Comment by ronnac** [comment]
I ran pkg update today and it installed the new r-base 3.6.1-2. This problem seems to be fixed. However, when I quit and save the R session I get a new error message:
> q()
Save workspace image? [y/n/c]: y
sh: 1: Syntax error: Unterminated quoted string
$

**Comment by its-pointless** [comment]
yeah i have already fixed that.
