### ISSUE TITLE
Error when trying to import cv2

### ISSUE THREAD

**Issue by YEDrekt** [its-pointless/its-pointless.github.io#38]
Hello, I installed opencv for Python with `pkg install opencv` from this repository. But when I try to
`import cv2` in Python 3.7.5, it gives me this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cv2/_init_.py", line 89, in <module>
    bootstrap()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/cv2/_init_.py", line 79, in bootstrap
    import cv2
ImportError: dlopen failed: library "libpng16.so" not found
`
Any idea to fix this?

**Comment by its-pointless** [comment]
Its likely you are using rhe wrong repo
Use  https://its-pointless.github.io/files/24 instead of  https://its-pointless.github.io/files
This means my installl setuo repo script is broken. Will fix that.

**Comment by YEDrekt** [comment]
I just followed the steps in [here](https://wiki.termux.com/wiki/Package_Management). How can I use https://its-pointless.github.io/files/24 instead of https://its-pointless.github.io/files ?

**Comment by its-pointless** [comment]
copy and paste here output from termux-info

**Comment by its-pointless** [comment]
And it will show me issue

**Comment by YEDrekt** [comment]
Here it is:
`Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://termux.org/packages stable/main
System information:
Linux localhost 4.9.148 #1 SMP PREEMPT Wed Oct 9 10:47:40 CST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
HUAWEI
Device model:
FIG-LX1`

**Comment by its-pointless** [comment]
Use text editor and open file $PREFIX/etc/apt/sources.list or $PREFIX/etc/apt/sources.list.d/pointless.list and change https://its-pointless.github.io/files to https://its-pointless.github.io/files/24

**Comment by YEDrekt** [comment]
Thank you, that solved my problem!
