### ISSUE TITLE
opencv for python3.8

### ISSUE THREAD

**Issue by Minecraftsxc** [its-pointless/its-pointless.github.io#40]
Increase opencv for python3.8

**Comment by its-pointless** [comment]
Its available for android 7 and above using its-pointless.github.io/files/24 as apt archive
Do you want to use it for android 5 or 6?

**Comment by Minecraftsxc** [comment]
> Its available for android 7 and above using its-pointless.github.io/files/24 as apt archive
> Do you want to use it for android 5 or 6?

I using Android10.

**Comment by its-pointless** [comment]
should be fixed
