### ISSUE TITLE
Octave cannot find libandroid-support

### ISSUE THREAD

**Issue by HJarausch** [its-pointless/its-pointless.github.io#42]
Hi,
after termux-repo-update Octave doesn't start anymore. It cannot find libandroid-support.so.
The same happens on a fresh install of Termux under Android 9.

**Comment by its-pointless** [comment]
you need to update the repo location. in the etc/apt/sources.list  change 
`
https://its-pointless.github.io/files/

`
To https://its-pointless.github.io/files/24/

**Comment by HJarausch** [comment]
Thanks,
octave is working fine now.
But now, ecl suffers from the same problem.
Is there any fix?

**Comment by its-pointless** [comment]
just running ecl is broken for you?

**Comment by its-pointless** [comment]
try
`apt install ecl --reinstall`

**Comment by HJarausch** [comment]
I had to remove the .cache folder in my home folder.
Now it works.
Sorry for the noise,
A Happy New Year to you,
Helmut
