### ISSUE TITLE
vlc termux build crashes segmentation fault.

### ISSUE THREAD

**Issue by macerg** [its-pointless/its-pointless.github.io#47]
Hello, I hope I've come to the right place for this issue!
![Screenshot_20200211-093740__01](https://user-images.githubusercontent.com/4559048/74220221-920e8880-4ce1-11ea-9a01-bfcac2be634b.jpg)
 I've installed the termux build of vlc (from extras, I believe). It works fine on 'local' media but crashes with 'segmentation fault' on adding an http stream.  See attachment. 
Running under Android 10.3 on OnePlus 6. 
Help much appreciated.
Thanks in anticipation.

**Comment by macerg** [comment]
Bump.  pleasy please take a look.

**Comment by its-pointless** [comment]
updated vlc. should work. Also now utilizes libsmb2 so streaming from windows or samba shares should work.

**Comment by macerg** [comment]
That's 'fixed' in that most streams from my servers work ok. Streams from mpd all work. Interestingly, live radio stream from VLC on my server does not work on this build. It does on VLC Android and VLC on my Ubuntu VLC (3.0.8) Thanks for the 99%

**Comment by macerg** [comment]
Further to this, it would appear that the VLC stream (uncompressed, from my server) is being received but not decoded, perhaps this a missing codec?
![Screenshot_20200218-084742](https://user-images.githubusercontent.com/4559048/74696837-8d8b2800-522b-11ea-8002-2bd9205ae9c0.jpg)
![Screenshot_20200218-084345](https://user-images.githubusercontent.com/4559048/74696922-c3c8a780-522b-11ea-8f42-5d54a0eed3b7.jpg)

**Comment by macerg** [comment]
For information, 'sout' parameters on my 'sending' VLC:-
#Streamed radio
        sout="--sout '#std{scodec=dvbs,soverlay,access=http,mux=ts,dst=:1239} --no-video --sout-all --sout-keep'".  This works just fine on my 'other' VLC's, also even to mpv and other players. By great if you can fix this. Thanks again.

**Comment by macerg** [comment]
mpv playing the stream.
![Screenshot_20200218-093004__01](https://user-images.githubusercontent.com/4559048/74698764-849d5500-5231-11ea-8718-c876eb06d5f6.jpg)

**Comment by its-pointless** [comment]
is audio not decoding on some streams but you are getting sound from some streams but not others via vlc?
is using pulseaudio output instead of opensles a better option?
im thinking of disabling the opensles plugin and just output via pulseaudio.

**Comment by macerg** [comment]
Audio is working on all but one audio streams (mpd and live BBC radio streams). I also have a stream from VLC which comes from a server which I use to send high bit rate radio to myself when I'm out of the UK. This is the only audio stream that doesn't play. It works fine in Android VLC and VLC on my Ubuntu machine. I have included my server's VLC 'sout' parameters in previous post.  Thanks for attention.

**Comment by macerg** [comment]
Hi again, you can put a hold onto investigations on this if you want to. Something very strange is happening on the BBC radio streams, for example, the following URL works just fine on my android VLC but not on any other of my VLC's, including yours.:-
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8

**Comment by macerg** [comment]
Hello, I don't know whether this is a factor or not. It would appear that the BBC have changed the format of their radio streams. The only VLC  I have that still plays them is VLC Android which is 3.2.8, my Ubuntu VLC's are 3.0.8, yours is 3.0.9.

**Comment by macerg** [comment]
Ok, an update, the previous posts regarding other VLC's on my server were a 'red herring'. There were issues with my server internet.

The situation with your VLC is this, is will not play BBC radio streams. These play fine on other media players, such as mpv. An example stream is this one:- http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8  attached is a screenshot of mpv playing the stream. I would be prepared to make a donation if this can be fixed please.
![Screenshot_20200219-100546](https://user-images.githubusercontent.com/4559048/74798185-a238f000-52ff-11ea-81de-78bace5e0a42.jpg)

**Comment by its-pointless** [comment]
updated and working on my end

**Comment by macerg** [comment]
Well, I've updated:-
VLC media player 3.0.9 Vetinari (revision 22)
And issue is still the same.
Play this stream on mpv :-
http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8 
Then try with vlc.  Thanks for the try though.

**Comment by its-pointless** [comment]
nvlc http://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/llnw/bbc_world_service.m3u8
and it starts playing

**Comment by macerg** [comment]
Ok, it works for you. Doesn't work for me though vlc or nvlc.

**Comment by its-pointless** [comment]
Install libdvbpsi i messed up depencies

**Comment by macerg** [comment]
Yes, that's done it! Thanks very much for that! Do you have a PayPal account? I want to send you a donation. One further request, any chance of compiling with the qt interface. Thanks again.

**Comment by macerg** [comment]
Thanks again as issue thankfully resolved. QT interface would be nice bonus😉

**Comment by macerg** [comment]
Thanks again.
