### ISSUE TITLE
About setup-pointless-repo.sh

### ISSUE THREAD

**Issue by angelog0** [its-pointless/its-pointless.github.io#49]
The script contains 

`mkdir $PREFIX/etc/apt/sources.list.d`

which will fail if the directory exists. I would suggest to add the `-p` option:

`mkdir -p $PREFIX/etc/apt/sources.list.d`

**Comment by angelog0** [comment]
I have seen that `setup-pointless-repo.sh` creates the file `pointless.gpg` in the user HOME. Really we need that file or can we delete it? If we really need it, would it be better to have an _hidden_ `.pointless.gpg`?

**Comment by joshcangit** [comment]
> I have seen that `setup-pointless-repo.sh` creates the file `pointless.gpg` in the user HOME. Really we need that file or can we delete it? If we really need it, would it be better to have an _hidden_ `.pointless.gpg`?

My pull request #50 should solve that.
I've used `if-else` for cURL and Wget but I'm not sure if I should have used `case`.
