### ISSUE TITLE
Repl of the julia don't work in arm

### ISSUE THREAD

**Issue by buribu** [its-pointless/its-pointless.github.io#5]
![screenshot_20180330-192705](https://user-images.githubusercontent.com/782908/38155887-a7b5e530-3450-11e8-8d22-20cb5c0ed119.png)

**Comment by its-pointless** [comment]
quick fix... 
ln -s /data/data/com.termux/files/usr/opt/julia/julia-f681c22353/lib/julia/libdSFMT.so /data/data/com.termux/files/usr/lib/libdSFMT.so

**Comment by its-pointless** [comment]
I only got it working yesterday so its likely to be buggy...
