### ISSUE TITLE
Error for ELF64_ST_TYPE

### ISSUE THREAD

**Issue by 1petro** [its-pointless/its-pointless.github.io#51]
i tried to compile linux kernel for poco f1 android 9 with  my phone poco kernel version 4.9 i started make defconfig i got some warnings after that make gived me lots of warnings for ELF I dunno is that related to it full log is here https://del.dog/elferror.txt maybe i missed something thx

**Comment by its-pointless** [comment]
That should be defined by the linux kernel source. It would require me going through linux source code to fix this. I don't really want to deal with that.
