### ISSUE TITLE
gpg key expired

### ISSUE THREAD

**Issue by landfillbaby** [its-pointless/its-pointless.github.io#54]
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://its-pointless.github.io/files/24 termux InRelease: The following signatures were invalid: EXPKEYSIG 906F5AFA9A32C72D its pointless <itspointless@redchan.it>

**Comment by its-pointless** [comment]
Yeah im about to change keys some time today.

**Comment by landfillbaby** [comment]
alright cool! you fixed it

**Comment by its-pointless** [comment]
key updated..
