### ISSUE TITLE
CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by zcatav** [its-pointless/its-pointless.github.io#56]
I use R on Termux.
After updating libicu R does'nt work anymore. It throws "CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/lib/R/bin/exec/R": library "libicuuc.so.65" not found" error.

find /data/data/com.termux/files/usr -name libicuuc*
/data/data/com.termux/files/usr/lib/libicuuc.so.66.1
/data/data/com.termux/files/usr/lib/libicuuc.so
/data/data/com.termux/files/usr/lib/libicuuc.so.66

# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.4.113-Lineage-g4be112c9d7e #1 SMP PREEMPT Tue Mar 10 00:16:27 UTC 2020 armv7l Android

R needs previous version of libicu but its updated.
Thanks in advance.

**Comment by its-pointless** [comment]
apt update and apt upgrade 
it should work 
if apt still won't work download its-pointless.github.io/pointless.gpg to termux and use 
`apt-key add pointless.gpg` 
then try apt update  then apt upgrade

**Comment by zcatav** [comment]
Thanks. It works with gpg key renewing.
