### ISSUE TITLE
Julia 1.5.1 crashes on start up on Nexus 5X

### ISSUE THREAD

**Issue by fusion809** [its-pointless/its-pointless.github.io#66]
Hi,

Very grateful that someone is maintaining a Julia package for Termux. Unfortunately the Julia 1.5.1 package crashes on start up for me, here's a screenshot of the error. My preferred shell is Zsh, and in it the error is "invalid system call julia". In Bash I get the error shown in this screenshot.

![Screenshot_20200906-010255777](https://user-images.githubusercontent.com/4717341/92308002-b31c2b00-efdd-11ea-988d-61d0e8025665.jpg)

Thanks for your time

**Comment by its-pointless** [comment]
Try getting this version 
https://github.com/its-pointless/gcc_termux/blob/master/julia_1.5.1_aarch64.deb 
and install it
dpkg -i julia_1.5.1_aarch64.deb

**Comment by fusion809** [comment]
I get the same error with it installed I'm afraid.

**Comment by fusion809** [comment]
I've run strace to give more useful debugging info, here's the log: https://gist.github.com/fusion809/26fa0a5529387ce6e371f506cd2fed15 (I ran `strace julia &> julia_strace.log` to get this log, in case the precise command is relevant).

**Comment by fusion809** [comment]
I should say I use the Pixel Experience ROM (with version 10 of Android), in case that's relevant. But all other Termux packages seem to work fine, like I've been able to install Zsh, Python, Ruby, R and GNU Octave and they all seem to work fine.

**Comment by its-pointless** [comment]
try https://github.com/its-pointless/gcc_termux/blob/master/libjulia.so.1.5 and replace it in usr/opt/julia/lib/libjulia.so.1.5

**Comment by fusion809** [comment]
I'm afraid that failed to correct the problem too, here's a screenshot showing the precise error. 
![Screenshot_20200909-162349629](https://user-images.githubusercontent.com/4717341/92562319-1eede480-f2b9-11ea-9247-13350948c75e.jpg)

**Comment by fusion809** [comment]
It starts now. Thanks!
