### ISSUE TITLE
Scipy and numpy for Python 3.9

### ISSUE THREAD

**Issue by mvolfik** [its-pointless/its-pointless.github.io#68]
Termux has updated python3 to 3.9, but this repository installs numpy and scipy in `/usr/lib/python3.8/site-packages/`, and when I try to install some numpy/scipy dependent package, pip tries to build these.

When will the packages be available for Python 3.9?

Thanks a lot.

**Comment by its-pointless** [comment]
Should be fixed

**Comment by mvolfik** [comment]
Confirmed, thanks
