### ISSUE TITLE
Mongo DB error

### ISSUE THREAD

**Issue by Leech777** [its-pointless/its-pointless.github.io#76]
Error message:`CANNOT LINK EXECUTABLE "mongo": library "libicudata.so.67" not found`

Steps to reproduce
1. Used setup-pointless-repo.sh script.
2. Run `apt install mongodb`
3. Package got installed.
4. Run mongodb and got the error.
5. Run mongo too and had same error.

Any reason??

**Comment by its-pointless** [comment]
should be fixed
