### ISSUE TITLE
Gcc build error

### ISSUE THREAD

**Issue by Saikatsaha1996** [its-pointless/its-pointless.github.io#85]
![Screenshot_2021-06-28-19-18-09-688_com termux](https://user-images.githubusercontent.com/72664192/123648284-73f9e780-d846-11eb-8c5f-7c6c60ec3238.jpg)

**Comment by virtual-designer** [comment]
I think you saved the wrong URL into `sources.list` file.
Add this to `sources.list`: 
```
deb [trusted=yes]  https://its-pointless.github.io/files/24 termux extras
``` 
Then run `apt update`. This should work fine.

**Comment by Saikatsaha1996** [comment]
Yes now working but I am facing some problem when compile c codes.. showing no C99 available.. 
But I want to...
☹️

**Comment by virtual-designer** [comment]
For this reason, gcc is not recommended for termux, use clang instead. I've a very bad experience with gcc on termux 😠. Clang has almost every features of gcc and all of the termux packages are built using that. So, please use clang.

**Comment by Saikatsaha1996** [comment]
> For this reason, gcc is not recommended for termux, use clang instead. I've a very bad experience with gcc on termux 😠. Clang has almost every features of gcc and all of the termux packages are built using that. So, please use clang.

Actually some code can't compile with clang ☹️

**Comment by Saikatsaha1996** [comment]
> For this reason, gcc is not recommended for termux, use clang instead. I've a very bad experience with gcc on termux 😠. Clang has almost every features of gcc and all of the termux packages are built using that. So, please use clang.

And I found one more unofficial gcc 10.2.0 
And it works.. but mey b it have some bugs I asked developer ... He told me he wants some free time to slove it..
