### ISSUE TITLE
g++ package dependency error

### ISSUE THREAD

**Issue by asnelt** [its-pointless/its-pointless.github.io#9]
Trying to install g++ on a fresh install of termux (with just wget installed as an additional package and the setup-pointless-repo.sh script applied) fails with conflicting dependencies:

Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 guile-2.2 : Conflicts: guile but 2.0.14 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by its-pointless** [comment]
Updated should be fixed?

**Comment by asnelt** [comment]
It is working! Many thanks!
